/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.projetofazenda;

import service.TipoServicoRepositoryJson;
import model.TipoServico;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class GerenciarServicosDialog extends javax.swing.JDialog {

    
    private TipoServicoRepositoryJson repository;
    private java.util.List<TipoServico> servicos;
    private DefaultListModel<String> listModel;

    /**
     * Creates new form GerenciarServicosDialog
     */
   public GerenciarServicosDialog(
        java.awt.Frame parent,
        boolean modal,
        TipoServicoRepositoryJson repository
) {
    super(parent, modal);

    initComponents();

    this.repository = repository;

    listModel = new DefaultListModel<>();
    listaServicos.setModel(listModel);

    carregarServicos();
}
    
    private void carregarServicos() {

    servicos = repository.listarTodos();

    listModel.clear();

    for (TipoServico servico : servicos) {

        String status = servico.isAtivo()
                ? "ativo"
                : "inativo";

        String carga;

        if (servico.getCargaHoraria() > 0) {
            carga = servico.getCargaHoraria() + "h";
        } else {
            carga = "sem carga";
        }

        listModel.addElement(
                servico.getDescricao()
                + " - "
                + carga
                + " - "
                + status
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNomeServico = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtCargaHoraria = new javax.swing.JTextPane();
        chkAtivo = new javax.swing.JRadioButton();
        btnNovo = new javax.swing.JToggleButton();
        btnSalvar = new javax.swing.JToggleButton();
        btnAtivarDesativar = new javax.swing.JToggleButton();
        btnFechar = new javax.swing.JToggleButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaServicos = new javax.swing.JList<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setViewportView(jEditorPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jScrollPane6.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lista de Servicos:");

        jLabel2.setText("Nome do servico:");

        jScrollPane3.setViewportView(txtNomeServico);

        jLabel3.setText("Carga horaria:");

        jScrollPane5.setViewportView(txtCargaHoraria);

        chkAtivo.setText("Servico em atividade");
        chkAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtivoActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo servico");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAtivarDesativar.setText("Ativar/desativar");
        btnAtivarDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtivarDesativarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar janela");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        listaServicos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaServicos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaServicosValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(listaServicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(chkAtivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAtivarDesativar)
                    .addComponent(btnFechar))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addComponent(chkAtivo)
                        .addGap(20, 20, 20)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar)
                        .addGap(12, 12, 12)
                        .addComponent(btnAtivarDesativar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAtivoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
         String nomeServico =
            txtNomeServico.getText().trim();

    if (nomeServico.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Informe o nome do serviço."
        );
        return;
    }

    int cargaHoraria;

    try {
        cargaHoraria = Integer.parseInt(
                txtCargaHoraria.getText().trim()
        );
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(
                this,
                "Carga horária inválida. Use apenas números."
        );
        return;
    }

    if (cargaHoraria < 0) {
        JOptionPane.showMessageDialog(
                this,
                "A carga horária não pode ser negativa."
        );
        return;
    }

    int indice = listaServicos.getSelectedIndex();

    if (indice < 0) {

        repository.adicionarServico(
                nomeServico,
                cargaHoraria
        );

        JOptionPane.showMessageDialog(
                this,
                "Serviço adicionado com sucesso!"
        );

    } else {

        TipoServico servico =
                servicos.get(indice);

        servico.setDescricao(nomeServico);
        servico.setCargaHoraria(cargaHoraria);
        servico.setAtivo(chkAtivo.isSelected());

        repository.atualizarServico(servico);

        JOptionPane.showMessageDialog(
                this,
                "Serviço atualizado com sucesso!"
        );
    }

    carregarServicos();

    listaServicos.clearSelection();

    txtNomeServico.setText("");
    txtCargaHoraria.setText("0");
    chkAtivo.setSelected(true);
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void listaServicosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaServicosValueChanged
       
        if (evt.getValueIsAdjusting()) {
        return;
    }

    int indice = listaServicos.getSelectedIndex();

    if (indice < 0) {
        return;
    }

    TipoServico servico = servicos.get(indice);

    txtNomeServico.setText(servico.getDescricao());

    txtCargaHoraria.setText(
            String.valueOf(servico.getCargaHoraria())
    );

    chkAtivo.setSelected(servico.isAtivo());
        
    }//GEN-LAST:event_listaServicosValueChanged

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
      
         listaServicos.clearSelection();

    txtNomeServico.setText("");
    txtCargaHoraria.setText("0");
    chkAtivo.setSelected(true);

    txtNomeServico.requestFocus();
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAtivarDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarDesativarActionPerformed
        
        int indice = listaServicos.getSelectedIndex();

    if (indice < 0) {
        JOptionPane.showMessageDialog(
                this,
                "Selecione um serviço."
        );
        return;
    }

    TipoServico servico =
            servicos.get(indice);

    boolean novoStatus =
            !servico.isAtivo();

    repository.alterarStatusServico(
            servico.getId(),
            novoStatus
    );

    carregarServicos();

    JOptionPane.showMessageDialog(
            this,
            novoStatus
                    ? "Serviço ativado com sucesso!"
                    : "Serviço desativado com sucesso!"
    );
        
    }//GEN-LAST:event_btnAtivarDesativarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_btnFecharActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               GerenciarServicosDialog dialog =
        new GerenciarServicosDialog(
                new javax.swing.JFrame(),
                true,
                new TipoServicoRepositoryJson()
        );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAtivarDesativar;
    private javax.swing.JToggleButton btnFechar;
    private javax.swing.JToggleButton btnNovo;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JRadioButton chkAtivo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTree jTree1;
    private javax.swing.JList<String> listaServicos;
    private javax.swing.JTextPane txtCargaHoraria;
    private javax.swing.JTextPane txtNomeServico;
    // End of variables declaration//GEN-END:variables
}
